name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Move built jars
        run: |
          mkdir staging
          mv target staging/parent
          mv bukkit/target staging/bukkit
          mv bungee/target staging/bungee
          mv common/target staging/common
          mv paper/target staging/paper
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: Package
          path: staging
